#

workflows:
    dts:
        metadata:
            title: 'DTS 流程'
        places:
            post:
                metadata:
                    name: '创建'
                    auth: 'dts_auth_any'
                    branchA: 'A'
                    view:
                        isCheck: false
                        isReview: false
                        isCreator: false
            check:
                metadata:
                    name: '检查'
                    auth: 'dts_auth_check'
                    branchA: 'A'
                    view:
                        isCheck: true
                        isReview: false
                        isCreator: false
            review:
                metadata:
                    name: '审核'
                    auth: 'dts_auth_review'
                    branchA: 'A'
                    view:
                        isCheck: false
                        isReview: true
                        isCreator: false
            resolve:
                metadata:
                    name: '解决'
                    branchA: 'A'
                    view:
                        isCheck: false
                        isReview: false
                        isCreator: true
            close:
                metadata:
                    name: '关闭'
                    branchA: 'A'
                    view:
                        isCheck: false
                        isReview: false
                        isCreator: false
            cancel:
                metadata:
                    name: '取消'
                    auth: 'dts_auth_review'
                    view:
                        isCheck: false
                        isReview: false
                        isCreator: false
        transitions:
            to_check:
                from: post
                to:   check
                metadata:
                    role: 'WF_ALL'
            to_review:
                from: check
                to:   review
                metadata:
                    role: 'WF_ALL'
            to_resolve:
                from: review
                to:   resolve
                metadata:
                    role: 'WF_ALL'
            to_close:
                from: resolve
                to:   close
                metadata:
                    role: 'WF_ALL'
            to_cancel:
                from: [check, review]
                to:   cancel
                metadata:
                    role: 'WF_ALL'
