#

workflows:
    dts:
        metadata:
            title: 'DTS 工作流'
        places:
            suspend:
                metadata:
                    name: '挂起'
                    line: ['suspend']
                    allow:
                        updateProgress: false
                        suspend: false
                        cancel: false
                        showRmvAttachmentIcon: false
            working:
                metadata:
                    name: '处理中'
                    line: ['main', 'suspend', 'cancel']
                    allow:
                        updateProgress: true
                        suspend: true
                        cancel: true
                        showRmvAttachmentIcon: true
            resolve:
                metadata:
                    name: '解决'
                    line: ['main', 'suspend']
                    allow:
                        updateProgress: false
                        suspend: false
                        cancel: false
                        showRmvAttachmentIcon: true
            close:
                metadata:
                    name: '关闭'
                    line: ['main', 'suspend']
                    allow:
                        updateProgress: false
                        suspend: false
                        cancel: false
                        showRmvAttachmentIcon: false
            cancel:
                metadata:
                    name: '取消'
                    line: ['cancel']
                    allow:
                        updateProgress: false
                        suspend: false
                        cancel: false
                        showRmvAttachmentIcon: false
        transitions:
            to_working:
                from: [resolve, close, suspend]
                to:   working
            to_resolve:
                from: working
                to:   resolve
            to_close:
                from: resolve
                to:   close
            to_suspend:
                from: working
                to:   suspend
            to_cancel:
                from: working
                to:   cancel
