#

workflows:
    dts:
        metadata:
            title: 'DTS 工作流'
        places:
            create:
                metadata:
                    name: '新建'
                    line: 'main'
                    allow:
                        updateProgress: true
                        showRmvAttachmentIcon: true
            working:
                metadata:
                    name: '处理中'
                    line: 'main'
                    allow:
                        updateProgress: true
                        showRmvAttachmentIcon: true
            resolve:
                metadata:
                    name: '解决'
                    line: 'main'
                    allow:
                        updateProgress: false
                        showRmvAttachmentIcon: true
            close:
                metadata:
                    name: '关闭'
                    line: 'main'
                    allow:
                        updateProgress: false
                        showRmvAttachmentIcon: false
        transitions:
            to_working:
                from: [create, resolve, close]
                to:   working
                metadata:
                    role: 'WF_ALL'
            to_resolve:
                from: working
                to:   resolve
                metadata:
                    role: 'WF_ALL'
            to_close:
                from: resolve
                to:   close
                metadata:
                    role: 'WF_ALL'
