#

workflows:
    dts:
        metadata:
            title: 'DTS 工作流'
        places:
            suspend:
                metadata:
                    name: '挂起'
                    line: 'branch'
                    allow:
                        updateProgress: false
                        suspend: false
                        showRmvAttachmentIcon: false
            working:
                metadata:
                    name: '处理中'
                    line: 'main'
                    allow:
                        updateProgress: true
                        suspend: true
                        showRmvAttachmentIcon: true
            resolve:
                metadata:
                    name: '解决'
                    line: 'main'
                    allow:
                        updateProgress: false
                        suspend: false
                        showRmvAttachmentIcon: true
            close:
                metadata:
                    name: '关闭'
                    line: 'main'
                    allow:
                        updateProgress: false
                        suspend: false
                        showRmvAttachmentIcon: false
        transitions:
            to_working:
                from: [resolve, close, suspend]
                to:   working
            to_resolve:
                from: working
                to:   resolve
            to_close:
                from: resolve
                to:   close
            to_suspend:
                from: working
                to:   suspend
