#

workflows:
    dts:
        metadata:
            title: 'DTS 流程'
        places:
            create:
                metadata:
                    name: '新建'
                    allow:
                        updateProgress: true
            working:
                metadata:
                    name: '处理中'
                    allow:
                        updateProgress: true
            resolve:
                metadata:
                    name: '解决'
                    allow:
                        updateProgress: false
            close:
                metadata:
                    name: '关闭'
                    allow:
                        updateProgress: false
            cancel:
                metadata:
                    name: '取消'
                    allow:
                        updateProgress: false
        transitions:
            to_working:
                from: create
                to:   working
                metadata:
                    role: 'WF_ALL'
            to_resolve:
                from: working
                to:   resolve
                metadata:
                    role: 'WF_ALL'
            to_close:
                from: resolve
                to:   close
                metadata:
                    role: 'WF_ALL'
            to_cancel:
                from: [working]
                to:   cancel
                metadata:
                    role: 'WF_ALL'
