#

workflows:
    dts:
        metadata:
            title: 'DTS 流程'
        places:
            create:
                metadata:
                    name: '创建'
                    auth: 'dts_auth_any'
                    branchA: 'A'
                    view:
                        isCheck: false
                        isReview: false
                        isCreator: false
            handling:
                metadata:
                    name: '处理中'
                    auth: 'dts_auth_handling'
                    branchA: 'A'
                    view:
                        isCheck: true
                        isReview: false
                        isCreator: false
            resolve:
                metadata:
                    name: '解决'
                    auth: 'dts_auth_any'
                    branchA: 'A'
                    view:
                        isCheck: false
                        isReview: false
                        isCreator: true
            close:
                metadata:
                    name: '关闭'
                    auth: 'dts_auth_any'
                    branchA: 'A'
                    view:
                        isCheck: false
                        isReview: false
                        isCreator: false
            cancel:
                metadata:
                    name: '取消'
                    auth: 'dts_auth_any'
                    view:
                        isCheck: false
                        isReview: false
                        isCreator: false
        transitions:
            to_handling:
                from: create
                to:   handling
                metadata:
                    role: 'WF_ALL'
            to_resolve:
                from: handling
                to:   resolve
                metadata:
                    role: 'WF_ALL'
            to_close:
                from: resolve
                to:   close
                metadata:
                    role: 'WF_ALL'
            to_cancel:
                from: [handling]
                to:   cancel
                metadata:
                    role: 'WF_ALL'
